version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python django_project/manage.py runserver 0.0.0.0:8000
    environment:
    - DATABASE_URL
    volumes:
    - .:/app
    ports:
    - 8000:8000
    depends_on:
    - db