# Generated by Django 3.1.3 on 2020-11-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractLoanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_value', models.FloatField()),
                ('emi_type', models.CharField(choices=[('Advance', 'Advance'), ('Arrears', 'Arrears')], max_length=30)),
                ('interest_rate', models.FloatField()),
                ('payment_recurrence_days', models.FloatField()),
                ('processing_charge', models.FloatField()),
                ('type_of_loan', models.CharField(choices=[('Personal loan', 'Personal loan'), ('Business loan', 'Business loan'), ('Home equity loan', 'Home equity loan')], max_length=40)),
                ('scheme', models.CharField(max_length=30)),
                ('total_period_of_loan_days', models.IntegerField()),
                ('collateral', models.CharField(max_length=50)),
                ('status', models.CharField(default='new', max_length=20)),
                ('loan_start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('abstractloanmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractloanmodel')),
            ],
            bases=('api.abstractloanmodel',),
        ),
        migrations.CreateModel(
            name='LoanSnapshotModel',
            fields=[
                ('abstractloanmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractloanmodel')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('api.abstractloanmodel',),
        ),
        migrations.CreateModel(
            name='LoanPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanmodel')),
            ],
        ),
    ]
